export { default as Landing } from 'pages/Landing/Landing'
export { default as ModalPage } from 'pages/Modal/SuccessModal'
export { default as PersonalInfo } from 'pages/Person&Laptop/PersonalInfo'
export { default as LaptopInfo } from 'pages/Person&Laptop/LaptopInfo'
export { default as EntriesList } from 'pages/EntriesList/EntriesList'
export { default as InfoPage } from 'pages/InfoPage/InfoPage'
